/* =========================================================
   medicines.js — Preloaded Real Medicine Data
   ========================================================= */

const PRELOADED_MEDICINES = [
  {
    id: 'med_001',
    name: 'Dolo 650',
    brand: 'Micro Labs',
    ingredients: 'Paracetamol 650mg',
    barcode: '123456',
    batch: 'DL-2026-A1',
    expiry: '2027-06-30',
    category: 'Analgesic / Antipyretic',
    dosageForm: 'Tablet',
    strength: '650mg',
    manufacturer: 'Micro Labs Ltd.',
    countryOfOrigin: 'India'
  },
  {
    id: 'med_002',
    name: 'Crocin Advance',
    brand: 'GSK',
    ingredients: 'Paracetamol 500mg',
    barcode: '789101',
    batch: 'CR-2026-B3',
    expiry: '2027-09-15',
    category: 'Analgesic / Antipyretic',
    dosageForm: 'Tablet',
    strength: '500mg',
    manufacturer: 'GlaxoSmithKline Pharmaceuticals Ltd.',
    countryOfOrigin: 'India'
  },
  {
    id: 'med_003',
    name: 'Augmentin 625',
    brand: 'GSK',
    ingredients: 'Amoxicillin + Clavulanic Acid',
    barcode: '111222',
    batch: 'AG-2026-D7',
    expiry: '2027-03-20',
    category: 'Antibiotic',
    dosageForm: 'Tablet',
    strength: '625mg',
    manufacturer: 'GlaxoSmithKline Pharmaceuticals Ltd.',
    countryOfOrigin: 'India'
  },
  {
    id: 'med_004',
    name: 'Azithral 500',
    brand: 'Alembic',
    ingredients: 'Azithromycin 500mg',
    barcode: '333444',
    batch: 'AZ-2026-F2',
    expiry: '2027-12-10',
    category: 'Antibiotic',
    dosageForm: 'Tablet',
    strength: '500mg',
    manufacturer: 'Alembic Pharmaceuticals Ltd.',
    countryOfOrigin: 'India'
  },
  {
    id: 'med_005',
    name: 'Evion 400',
    brand: 'Merck',
    ingredients: 'Vitamin E (Tocopheryl Acetate) 400mg',
    barcode: '555666',
    batch: 'EV-2026-G9',
    expiry: '2028-01-25',
    category: 'Vitamin Supplement',
    dosageForm: 'Capsule',
    strength: '400mg',
    manufacturer: 'Merck Ltd.',
    countryOfOrigin: 'India'
  },
  {
    id: 'med_006',
    name: 'Shelcal 500',
    brand: 'Torrent Pharma',
    ingredients: 'Calcium Carbonate + Vitamin D3',
    barcode: '777888',
    batch: 'SH-2026-H4',
    expiry: '2028-04-18',
    category: 'Calcium Supplement',
    dosageForm: 'Tablet',
    strength: '500mg',
    manufacturer: 'Torrent Pharmaceuticals Ltd.',
    countryOfOrigin: 'India'
  },
  {
    id: 'med_007',
    name: 'Limcee Vitamin C',
    brand: 'Abbott',
    ingredients: 'Ascorbic Acid (Vitamin C) 500mg',
    barcode: '999000',
    batch: 'LM-2026-J1',
    expiry: '2028-02-28',
    category: 'Vitamin Supplement',
    dosageForm: 'Chewable Tablet',
    strength: '500mg',
    manufacturer: 'Abbott India Ltd.',
    countryOfOrigin: 'India'
  },
  {
    id: 'med_008',
    name: 'Pantocid',
    brand: 'Sun Pharma',
    ingredients: 'Pantoprazole Sodium 40mg',
    barcode: '112233',
    batch: 'PT-2026-K6',
    expiry: '2027-08-05',
    category: 'Proton Pump Inhibitor',
    dosageForm: 'Tablet',
    strength: '40mg',
    manufacturer: 'Sun Pharmaceutical Industries Ltd.',
    countryOfOrigin: 'India'
  },
  {
    id: 'med_009',
    name: 'Disprin',
    brand: 'Reckitt',
    ingredients: 'Aspirin 350mg',
    barcode: '445566',
    batch: 'DS-2026-L8',
    expiry: '2027-11-30',
    category: 'Analgesic / Anti-inflammatory',
    dosageForm: 'Dispersible Tablet',
    strength: '350mg',
    manufacturer: 'Reckitt Benckiser Healthcare Ltd.',
    countryOfOrigin: 'India'
  },
  {
    id: 'med_010',
    name: 'Benadryl Syrup',
    brand: 'Johnson & Johnson',
    ingredients: 'Diphenhydramine Hydrochloride',
    barcode: '778899',
    batch: 'BD-2026-M3',
    expiry: '2027-07-22',
    category: 'Antihistamine / Cough Suppressant',
    dosageForm: 'Syrup',
    strength: '14.08mg/5ml',
    manufacturer: 'Johnson & Johnson Pvt. Ltd.',
    countryOfOrigin: 'India'
  },
  {
    id: 'med_011',
    name: 'Combiflam',
    brand: 'Sanofi',
    ingredients: 'Ibuprofen 400mg + Paracetamol 325mg',
    barcode: '334455',
    batch: 'CF-2026-N5',
    expiry: '2027-10-14',
    category: 'Analgesic / Anti-inflammatory',
    dosageForm: 'Tablet',
    strength: '400mg + 325mg',
    manufacturer: 'Sanofi India Ltd.',
    countryOfOrigin: 'India'
  },
  {
    id: 'med_012',
    name: 'Cetrizine (Zyrtec)',
    brand: 'UCB Pharma',
    ingredients: 'Cetirizine Dihydrochloride 10mg',
    barcode: '667788',
    batch: 'ZR-2026-P7',
    expiry: '2028-05-10',
    category: 'Antihistamine',
    dosageForm: 'Tablet',
    strength: '10mg',
    manufacturer: 'UCB India Pvt. Ltd.',
    countryOfOrigin: 'India'
  }
];
